### ISSUE TITLE
Use cover position instead of tilt position

### ISSUE THREAD

**Issue by Erbengi** [jirutka/hass-smarwi#16]
Wouldn't be better to use a cover position instead of a cover tilt position? For example, rename the `current_cover_tilt_position' method to `current_cover_position'. Currently it looks like you are controlling a blind:

![image](https://github.com/user-attachments/assets/e6863416-443c-409e-afad-1e464eace9be)

With a cover position, it looks like you are controlling a window position:
![image](https://github.com/user-attachments/assets/ad9d1537-1396-4ece-a1a3-168c49f70e8c)

**Comment by jirutka** [comment]
Smarwi is designed to open the window on the ventilation, i.e. _tilt_ it, so I think that `cover_tilt` is more appropriate here. I don’t know why it’s visually represented in this way though.

**Comment by Erbengi** [comment]
Okay, thank you. It's a Home Assistant problem. Let's close this issue.
